--===================================================
--
--				GHQ_ObjectiveAPI
--  			GHQ_ObjectiveAPI.lua
--
--	  API offering functions for Quest
--
-- 	  (c)2013 The Gryphonheart Team
--			All rights reserved
--===================================================