--TargetFile: BlizzardApi.lua
BlizzardApi.Events = {
	SystemEvent = {
		ADDON_ACTION_BLOCKED = "ADDON_ACTION_BLOCKED",
		ADDON_ACTION_FORBIDDEN = "ADDON_ACTION_FORBIDDEN",
		ADDON_LOADED = "ADDON_LOADED",
		VARIABLES_LOADED = "VARIABLES_LOADED",
	},
};