--TargetFile: BlizzardApi.lua
BlizzardApi.WidgetEnums = {
	AlphaMode = {
		DISABLE = "DISABLE",
		BLEND = "BLEND",
		ALPHAKEY = "ALPHAKEY",
		ADD = "ADD",
		MOD = "MOD",
	},
	ButtonState = {
		PUSHED = "PUSHED",
		NORMAL = "NORMAL",
	},
	ClickType = {
		LeftButtonUp = "LeftButtonUp",
		RightButtonUp = "RightButtonUp",
		MiddleButtonUp = "MiddleButtonUp",
		Button4Up = "Button4Up",
		Button5Up = "Button5Up",
		LeftButtonDown = "LeftButtonDown",
		RightButtonDown = "RightButtonDown",
		MiddleButtonDown = "MiddleButtonDown",
		Button4Down = "Button4Down",
		Button5Down = "Button5Down",
		AnyUp = "AnyUp",
		AnyDown = "AnyDown",
	},
	FramePoint = {
		TOPLEFT = "TOPLEFT",
		TOPRIGHT = "TOPRIGHT",
		BOTTOMLEFT = "BOTTOMLEFT",
		BOTTOMRIGHT = "BOTTOMRIGHT",
		TOP = "TOP",
		BOTTOM = "BOTTOM",
		LEFT = "LEFT",
		RIGHT = "RIGHT",
		CENTER = "CENTER"
	},
	FrameStrata = {
		PARENT = "PARENT",
		BACKGROUND = "BACKGROUND",
		LOW = "LOW",
		MEDIUM = "MEDIUM",
		HIGH = "HIGH",
		DIALOG = "DIALOG",
		FULLSCREEN = "FULLSCREEN",
		FULLSCREEN_DIALOG = "FULLSCREEN_DIALOG",
		TOOLTIP = "TOOLTIP",
	},
	FrameType = {
		Frame = "Frame",
		Button = "Button",
		EditBox = "EditBox",
		ScrollFrame = "ScrollFrame",
	},
	FrameHandler = {
		OnChar = "OnChar",
		OnDragStart = "OnDragStart",
		OnDragStop = "OnDragStop",
		OnEnter = "OnEnter",
		OnEvent = "OnEvent",
		OnHide = "OnHide",
		OnKeyDown = "OnKeyDown",
		OnKeyUp = "OnKeyUp",
		OnLeave = "OnLeave",
		OnLoad = "OnLoad",
		OnMouseDown = "OnMouseDown",
		OnMouseUp = "OnMouseUp",
		OnMouseWheel = "OnMouseWheel",
		OnReceiveDrag = "OnReceiveDrag",
		OnShow = "OnShow",
		OnSizeChanged = "OnSizeChanged",
		OnUpdate = "OnUpdate"
	},
	ButtonHandler = {
		OnClick = "OnClick",
		OnDoubleClick = "OnDoubleClick",
		PostClick = "PostClick",
		PreClick = "PreClick",
	},
	EditBoxHandler = {
		OnArrowPressed = "OnArrowPressed",
		OnCursorChanged = "OnCursorChanged",
		OnEditFocusGained = "OnEditFocusGained",
		OnEditFocusLost = "OnEditFocusLost",
		OnEnterPressed = "OnEnterPressed",
		OnEscapePressed = "OnEscapePressed",
		OnHyperlinkClick = "OnHyperlinkClick",
		OnHyperlinkEnter = "OnHyperlinkEnter",
		OnHyperlinkLeave = "OnHyperlinkLeave",
		OnInputLanguageChanged = "OnInputLanguageChanged",
		OnSpacePressed = "OnSpacePressed",
		OnTabPressed = "OnTabPressed",
		OnTextChanged = "OnTextChanged",
		OnTextSet = "OnTextSet",
	},
	JustifyH = {
		LEFT = "LEFT",
		RIGHT = "RIGHT",
		CENTER = "CENTER",
	},
	JustifyV = {
		TOP = "TOP",
		BOTTOM = "BOTTOM",
		CENTER = "CENTER",
	},
	Layer = {
		BACKGROUND = "BACKGROUND",
		BORDER = "BORDER",
		ARTWORK = "ARTWORK",
		OVERLAY = "OVERLAY",
		HIGHLIGHT = "HIGHLIGHT"
	},
	MouseButton = {
		RightButton = "RightButton",
		LeftButton = "LeftButton",
	},
	Orientation = {
		HORIZONTAL = "HORIZONTAL",
		VERTICAL = "VERTICAL",
	},
	TooltipAnchor = {
		ANCHOR_TOPRIGHT = "ANCHOR_TOPRIGHT",
		ANCHOR_RIGHT = "ANCHOR_RIGHT",
		ANCHOR_BOTTOMRIGHT = "ANCHOR_BOTTOMRIGHT",
		ANCHOR_TOPLEFT = "ANCHOR_TOPLEFT",
		ANCHOR_LEFT = "ANCHOR_LEFT",
		ANCHOR_BOTTOMLEFT = "ANCHOR_BOTTOMLEFT",
		ANCHOR_CURSOR = "ANCHOR_CURSOR",
		ANCHOR_PRESERVE = "ANCHOR_PRESERVE",
		ANCHOR_NONE = "ANCHOR_NONE",
	},
};